// Auto-generated — do not edit. Run build_words.py to regenerate.
const FRENCH_WORDS = [
  {fr:'de',en:'of, from'},
  {fr:'je',en:'I'},
  {fr:'est',en:'is'},
  {fr:'pas',en:'not'},
  {fr:'le',en:'the (masc.)'},
  {fr:'que',en:'that, what'},
  {fr:'la',en:'the (fem.)'},
  {fr:'vous',en:'you (formal/plural)'},
  {fr:'tu',en:'you (informal)'},
  {fr:'un',en:'a, one'},
  {fr:'et',en:'and'},
  {fr:'il',en:'he, it'},
  {fr:'ne',en:'not (first part of negation)'},
  {fr:'les',en:'the (plural)'},
  {fr:'en',en:'in, some'},
  {fr:'on',en:'we, one'},
  {fr:'une',en:'a, one (fem.)'},
  {fr:'ce',en:'this, it'},
  {fr:'pour',en:'for'},
  {fr:'qui',en:'who, which'},
  {fr:'mais',en:'but'},
  {fr:'dans',en:'in, inside'},
  {fr:'nous',en:'we'},
  {fr:'elle',en:'she'},
  {fr:'bien',en:'well, good'},
  {fr:'si',en:'if, yes (contradicting)'},
  {fr:'avec',en:'with'},
  {fr:'tout',en:'all, everything'},
  {fr:'plus',en:'more, plus'},
  {fr:'mon',en:'my (masc.)'},
  {fr:'fait',en:'done, made'},
  {fr:'moi',en:'me'},
  {fr:'oui',en:'yes'},
  {fr:'va',en:'goes, is going'},
  {fr:'faire',en:'to do, to make'},
  {fr:'ils',en:'they (masc.)'},
  {fr:'sur',en:'on, upon'},
  {fr:'comme',en:'like, as'},
  {fr:'être',en:'to be'},
  {fr:'ici',en:'here'},
  {fr:'ma',en:'my (fem.)'},
  {fr:'toi',en:'you (stressed)'},
  {fr:'dit',en:'said, told'},
  {fr:'lui',en:'him, to him'},
  {fr:'où',en:'where'},
  {fr:'là',en:'there'},
  {fr:'rien',en:'nothing'},
  {fr:'cette',en:'this (fem.)'},
  {fr:'sont',en:'are (they)'},
  {fr:'quand',en:'when'},
  {fr:'dire',en:'to say, to tell'},
  {fr:'son',en:'his, her, its'},
  {fr:'bon',en:'good'},
  {fr:'merci',en:'thank you'},
  {fr:'très',en:'very'},
  {fr:'jamais',en:'never'},
  {fr:'aussi',en:'also, too'},
  {fr:'avoir',en:'to have'},
  {fr:'vraiment',en:'really, truly'},
  {fr:'voir',en:'to see'},
  {fr:'même',en:'same, even'},
  {fr:'maintenant',en:'now'},
  {fr:'tous',en:'all (plural)'},
  {fr:'peut',en:'can (he/she)'},
  {fr:'deux',en:'two'},
  {fr:'peu',en:'little, few'},
  {fr:'temps',en:'time'},
  {fr:'toujours',en:'always'},
  {fr:'encore',en:'still, again'},
  {fr:'notre',en:'our'},
  {fr:'besoin',en:'need'},
  {fr:'vie',en:'life'},
  {fr:'aller',en:'to go'},
  {fr:'fois',en:'time (occurrence)'},
  {fr:'donc',en:'so, therefore'},
  {fr:'sans',en:'without'},
  {fr:'monde',en:'world'},
  {fr:'avant',en:'before'},
  {fr:'trop',en:'too much'},
  {fr:'père',en:'father'},
  {fr:'après',en:'after'},
  {fr:'homme',en:'man'},
  {fr:'femme',en:'woman, wife'},
  {fr:'vrai',en:'true'},
  {fr:'ans',en:'years'},
  {fr:'mal',en:'bad, pain'},
  {fr:'mère',en:'mother'},
  {fr:'petit',en:'small, little'},
  {fr:'maison',en:'house, home'},
  {fr:'jour',en:'day'},
  {fr:'autre',en:'other, another'},
  {fr:'nom',en:'name'},
  {fr:'nuit',en:'night'},
  {fr:'moins',en:'less, minus'},
  {fr:'maman',en:'mom'},
  {fr:'moment',en:'moment'},
  {fr:'seul',en:'alone, only'},
  {fr:'entre',en:'between'},
  {fr:'papa',en:'dad'},
  {fr:'peur',en:'fear'},
  {fr:'fils',en:'son'},
  {fr:'trois',en:'three'},
  {fr:'famille',en:'family'},
  {fr:'travail',en:'work, job'},
  {fr:'place',en:'place, square'},
  {fr:'fin',en:'end'},
  {fr:'eau',en:'water'},
  {fr:'terre',en:'earth, ground'},
  {fr:'belle',en:'beautiful (fem.)'},
  {fr:'mari',en:'husband'},
  {fr:'beau',en:'beautiful, handsome'},
  {fr:'argent',en:'money, silver'},
  {fr:'bonjour',en:'hello, good morning'},
  {fr:'raison',en:'reason'},
  {fr:'aide',en:'help'},
  {fr:'histoire',en:'story, history'},
  {fr:'ville',en:'city, town'},
  {fr:'ami',en:'friend'},
  {fr:'soir',en:'evening'},
  {fr:'matin',en:'morning'},
  {fr:'fille',en:'daughter, girl'},
  {fr:'gens',en:'people'},
  {fr:'partie',en:'part'},
  {fr:'question',en:'question'},
  {fr:'chambre',en:'room, bedroom'},
  {fr:'droit',en:'right, law'},
  {fr:'main',en:'hand'},
  {fr:'rue',en:'street'},
  {fr:'long',en:'long'},
  {fr:'noir',en:'black'},
  {fr:'roi',en:'king'},
  {fr:'livre',en:'book'},
  {fr:'pays',en:'country'},
  {fr:'guerre',en:'war'},
  {fr:'coeur',en:'heart'},
  {fr:'grand',en:'big, tall, great'},
  {fr:'grande',en:'big, tall (fem.)'},
  {fr:'jeune',en:'young'},
  {fr:'nouveau',en:'new (masc.)'},
  {fr:'nouvelle',en:'new (fem.)'},
  {fr:'premier',en:'first (masc.)'},
  {fr:'première',en:'first (fem.)'},
  {fr:'dernier',en:'last (masc.)'},
  {fr:'dernière',en:'last (fem.)'},
  {fr:'petite',en:'small (fem.)'},
  {fr:'bras',en:'arm'},
  {fr:'visage',en:'face'},
  {fr:'chemin',en:'path, way'},
  {fr:'fort',en:'strong, loud'},
  {fr:'haut',en:'high, top'},
  {fr:'bas',en:'low, bottom'},
  {fr:'corps',en:'body'},
  {fr:'yeux',en:'eyes'},
  {fr:'voix',en:'voice'},
  {fr:'frère',en:'brother'},
  {fr:'soeur',en:'sister'},
  {fr:'enfant',en:'child'},
  {fr:'enfants',en:'children'},
  {fr:'parents',en:'parents'},
  {fr:'école',en:'school'},
  {fr:'mois',en:'month'},
  {fr:'semaine',en:'week'},
  {fr:'heure',en:'hour'},
  {fr:'minute',en:'minute'},
  {fr:'an',en:'year'},
  {fr:'feu',en:'fire'},
  {fr:'route',en:'road'},
  {fr:'porte',en:'door'},
  {fr:'air',en:'air'},
  {fr:'côté',en:'side'},
  {fr:'point',en:'point, dot'},
  {fr:'mort',en:'death, dead'},
  {fr:'prix',en:'price, prize'},
  {fr:'ordre',en:'order'},
  {fr:'force',en:'strength, force'},
  {fr:'secret',en:'secret'},
  {fr:'lettre',en:'letter'},
  {fr:'jeu',en:'game'},
  {fr:'photo',en:'photograph'},
  {fr:'café',en:'coffee, café'},
  {fr:'verre',en:'glass'},
  {fr:'chien',en:'dog'},
  {fr:'lit',en:'bed'},
  {fr:'sac',en:'bag'},
  {fr:'carte',en:'card, map'},
  {fr:'âge',en:'age'},
  {fr:'groupe',en:'group'},
  {fr:'voyage',en:'trip, travel'},
  {fr:'musique',en:'music'},
  {fr:'film',en:'movie, film'},
  {fr:'bureau',en:'office, desk'},
  {fr:'voiture',en:'car'},
  {fr:'téléphone',en:'phone'},
  {fr:'hôpital',en:'hospital'},
  {fr:'police',en:'police'},
  {fr:'jardin',en:'garden'},
  {fr:'parler',en:'to speak, to talk'},
  {fr:'trouver',en:'to find'},
  {fr:'prendre',en:'to take'},
  {fr:'donner',en:'to give'},
  {fr:'penser',en:'to think'},
  {fr:'demander',en:'to ask'},
  {fr:'rester',en:'to stay, to remain'},
  {fr:'laisser',en:'to leave, to let'},
  {fr:'sortir',en:'to go out, to leave'},
  {fr:'commencer',en:'to begin, to start'},
  {fr:'aider',en:'to help'},
  {fr:'chercher',en:'to look for, to search'},
  {fr:'regarder',en:'to look at, to watch'},
  {fr:'attendre',en:'to wait'},
  {fr:'écouter',en:'to listen'},
  {fr:'entendre',en:'to hear'},
  {fr:'comprendre',en:'to understand'},
  {fr:'arrêter',en:'to stop'},
  {fr:'essayer',en:'to try'},
  {fr:'travailler',en:'to work'},
  {fr:'rentrer',en:'to return home'},
  {fr:'changer',en:'to change'},
  {fr:'entrer',en:'to enter'},
  {fr:'manger',en:'to eat'},
  {fr:'jouer',en:'to play'},
  {fr:'mourir',en:'to die'},
  {fr:'vivre',en:'to live'},
  {fr:'dormir',en:'to sleep'},
  {fr:'boire',en:'to drink'},
  {fr:'acheter',en:'to buy'},
  {fr:'payer',en:'to pay'},
  {fr:'gagner',en:'to win, to earn'},
  {fr:'perdre',en:'to lose'},
  {fr:'apprendre',en:'to learn'},
  {fr:'montrer',en:'to show'},
  {fr:'oublier',en:'to forget'},
  {fr:'tomber',en:'to fall'},
  {fr:'appeler',en:'to call'},
  {fr:'envoyer',en:'to send'},
  {fr:'tirer',en:'to pull, to shoot'},
  {fr:'garder',en:'to keep, to guard'},
  {fr:'occuper',en:'to occupy'},
  {fr:'sauver',en:'to save, to rescue'},
  {fr:'retrouver',en:'to find again'},
  {fr:'revenir',en:'to come back'},
  {fr:'partir',en:'to leave, to depart'},
  {fr:'tenir',en:'to hold'},
  {fr:'courir',en:'to run'},
  {fr:'porter',en:'to carry, to wear'},
  {fr:'mettre',en:'to put, to place'},
  {fr:'passer',en:'to pass, to spend (time)'},
  {fr:'devenir',en:'to become'},
  {fr:'servir',en:'to serve'},
  {fr:'suivre',en:'to follow'},
  {fr:'rendre',en:'to return, to give back'},
  {fr:'connaître',en:'to know (person/place)'},
  {fr:'savoir',en:'to know (fact)'},
  {fr:'croire',en:'to believe'},
  {fr:'vouloir',en:'to want'},
  {fr:'pouvoir',en:'to be able to, can'},
  {fr:'devoir',en:'to have to, must'},
  {fr:'aimer',en:'to love, to like'},
  {fr:'détester',en:'to hate'},
  {fr:'espérer',en:'to hope'},
  {fr:'ouvrir',en:'to open'},
  {fr:'fermer',en:'to close'},
  {fr:'lire',en:'to read'},
  {fr:'écrire',en:'to write'},
  {fr:'conduire',en:'to drive'},
  {fr:'choisir',en:'to choose'},
  {fr:'construire',en:'to build'},
  {fr:'casser',en:'to break'},
  {fr:'couper',en:'to cut'},
  {fr:'toucher',en:'to touch'},
  {fr:'sentir',en:'to feel, to smell'},
  {fr:'pleurer',en:'to cry'},
  {fr:'rire',en:'to laugh'},
  {fr:'chanter',en:'to sing'},
  {fr:'danser',en:'to dance'},
  {fr:'nager',en:'to swim'},
  {fr:'voler',en:'to fly, to steal'},
  {fr:'cacher',en:'to hide'},
  {fr:'brûler',en:'to burn'},
  {fr:'jeter',en:'to throw'},
  {fr:'pousser',en:'to push'},
  {fr:'tuer',en:'to kill'},
  {fr:'battre',en:'to beat, to fight'},
  {fr:'vendre',en:'to sell'},
  {fr:'asseoir',en:'to sit'},
  {fr:'lever',en:'to raise, to get up'},
  {fr:'monter',en:'to go up, to climb'},
  {fr:'descendre',en:'to go down'},
  {fr:'marcher',en:'to walk'},
  {fr:'expliquer',en:'to explain'},
  {fr:'raconter',en:'to tell (a story)'},
  {fr:'accepter',en:'to accept'},
  {fr:'refuser',en:'to refuse'},
  {fr:'décider',en:'to decide'},
  {fr:'proposer',en:'to propose, to suggest'},
  {fr:'réussir',en:'to succeed'},
  {fr:'continuer',en:'to continue'},
  {fr:'arranger',en:'to arrange, to fix'},
  {fr:'préparer',en:'to prepare'},
  {fr:'créer',en:'to create'},
  {fr:'utiliser',en:'to use'},
  {fr:'protéger',en:'to protect'},
  {fr:'rencontrer',en:'to meet'},
  {fr:'emmener',en:'to take (someone)'},
  {fr:'amener',en:'to bring (someone)'},
  {fr:'apporter',en:'to bring (thing)'},
  {fr:'emporter',en:'to take away'},
  {fr:'quitter',en:'to leave (a place/person)'},
  {fr:'manquer',en:'to miss'},
  {fr:'rappeler',en:'to call back, to remind'},
  {fr:'répondre',en:'to answer, to reply'},
  {fr:'poser',en:'to put down, to ask (question)'},
  {fr:'compter',en:'to count'},
  {fr:'imaginer',en:'to imagine'},
  {fr:'rêver',en:'to dream'},
  {fr:'souvenir',en:'to remember'},
  {fr:'oser',en:'to dare'},
  {fr:'mentir',en:'to lie'},
  {fr:'promener',en:'to walk (stroll)'},
  {fr:'voyager',en:'to travel'},
  {fr:'exister',en:'to exist'},
  {fr:'sembler',en:'to seem'},
  {fr:'paraître',en:'to appear, to seem'},
  {fr:'produire',en:'to produce'},
  {fr:'obtenir',en:'to obtain'},
  {fr:'recevoir',en:'to receive'},
  {fr:'offrir',en:'to offer, to give (gift)'},
  {fr:'permettre',en:'to allow, to permit'},
  {fr:'empêcher',en:'to prevent'},
  {fr:'risquer',en:'to risk'},
  {fr:'mériter',en:'to deserve'},
  {fr:'souffrir',en:'to suffer'},
  {fr:'supporter',en:'to bear, to support'},
  {fr:'intéresser',en:'to interest'},
  {fr:'plaire',en:'to please'},
  {fr:'réveiller',en:'to wake up'},
  {fr:'coucher',en:'to put to bed, to lie down'},
  {fr:'habiller',en:'to dress'},
  {fr:'laver',en:'to wash'},
  {fr:'inquiéter',en:'to worry'},
  {fr:'calmer',en:'to calm'},
  {fr:'améliorer',en:'to improve'},
  {fr:'développer',en:'to develop'},
  {fr:'participer',en:'to participate'},
  {fr:'représenter',en:'to represent'},
  {fr:'considérer',en:'to consider'},
  {fr:'reconnaître',en:'to recognize'},
  {fr:'appartenir',en:'to belong'},
  {fr:'exprimer',en:'to express'},
  {fr:'installer',en:'to install, to settle'},
  {fr:'présenter',en:'to present, to introduce'},
  {fr:'prêter',en:'to lend'},
  {fr:'étudier',en:'to study'},
  {fr:'enseigner',en:'to teach'},
  {fr:'dessiner',en:'to draw'},
  {fr:'peindre',en:'to paint'},
  {fr:'photographier',en:'to photograph'},
  {fr:'cuisiner',en:'to cook'},
  {fr:'nettoyer',en:'to clean'},
  {fr:'ranger',en:'to tidy up'},
  {fr:'réparer',en:'to repair, to fix'},
  {fr:'stationner',en:'to park'},
  {fr:'traverser',en:'to cross'},
  {fr:'tourner',en:'to turn'},
  {fr:'avancer',en:'to move forward'},
  {fr:'reculer',en:'to move backward'},
  {fr:'accélérer',en:'to accelerate'},
  {fr:'freiner',en:'to brake'},
  {fr:'personne',en:'person'},
  {fr:'garçon',en:'boy'},
  {fr:'bébé',en:'baby'},
  {fr:'monsieur',en:'sir, mister'},
  {fr:'madame',en:'madam, Mrs.'},
  {fr:'docteur',en:'doctor'},
  {fr:'capitaine',en:'captain'},
  {fr:'avocat',en:'lawyer'},
  {fr:'patron',en:'boss'},
  {fr:'chef',en:'chief, chef'},
  {fr:'président',en:'president'},
  {fr:'général',en:'general'},
  {fr:'professeur',en:'teacher, professor'},
  {fr:'étudiant',en:'student'},
  {fr:'voisin',en:'neighbor'},
  {fr:'inconnu',en:'stranger'},
  {fr:'ennemi',en:'enemy'},
  {fr:'victime',en:'victim'},
  {fr:'héros',en:'hero'},
  {fr:'voleur',en:'thief'},
  {fr:'soldat',en:'soldier'},
  {fr:'prisonnier',en:'prisoner'},
  {fr:'invité',en:'guest'},
  {fr:'client',en:'client, customer'},
  {fr:'collègue',en:'colleague'},
  {fr:'équipe',en:'team'},
  {fr:'couple',en:'couple'},
  {fr:'peuple',en:'people, nation'},
  {fr:'foule',en:'crowd'},
  {fr:'société',en:'society'},
  {fr:'tête',en:'head'},
  {fr:'cheveux',en:'hair'},
  {fr:'oeil',en:'eye'},
  {fr:'oreille',en:'ear'},
  {fr:'nez',en:'nose'},
  {fr:'bouche',en:'mouth'},
  {fr:'dent',en:'tooth'},
  {fr:'lèvre',en:'lip'},
  {fr:'langue',en:'tongue, language'},
  {fr:'gorge',en:'throat'},
  {fr:'épaule',en:'shoulder'},
  {fr:'dos',en:'back'},
  {fr:'ventre',en:'belly, stomach'},
  {fr:'jambe',en:'leg'},
  {fr:'genou',en:'knee'},
  {fr:'pied',en:'foot'},
  {fr:'doigt',en:'finger'},
  {fr:'ongle',en:'nail'},
  {fr:'peau',en:'skin'},
  {fr:'sang',en:'blood'},
  {fr:'os',en:'bone'},
  {fr:'cerveau',en:'brain'},
  {fr:'poumon',en:'lung'},
  {fr:'estomac',en:'stomach'},
  {fr:'cuisine',en:'kitchen'},
  {fr:'salon',en:'living room'},
  {fr:'salle',en:'room, hall'},
  {fr:'salle de bain',en:'bathroom'},
  {fr:'escalier',en:'staircase'},
  {fr:'mur',en:'wall'},
  {fr:'plafond',en:'ceiling'},
  {fr:'plancher',en:'floor'},
  {fr:'fenêtre',en:'window'},
  {fr:'toit',en:'roof'},
  {fr:'clé',en:'key'},
  {fr:'meuble',en:'furniture'},
  {fr:'chaise',en:'chair'},
  {fr:'table',en:'table'},
  {fr:'canapé',en:'couch, sofa'},
  {fr:'armoire',en:'wardrobe'},
  {fr:'miroir',en:'mirror'},
  {fr:'rideau',en:'curtain'},
  {fr:'lampe',en:'lamp'},
  {fr:'coussin',en:'cushion'},
  {fr:'tapis',en:'carpet, rug'},
  {fr:'pain',en:'bread'},
  {fr:'fromage',en:'cheese'},
  {fr:'viande',en:'meat'},
  {fr:'poisson',en:'fish'},
  {fr:'poulet',en:'chicken'},
  {fr:'oeuf',en:'egg'},
  {fr:'riz',en:'rice'},
  {fr:'pâtes',en:'pasta'},
  {fr:'soupe',en:'soup'},
  {fr:'salade',en:'salad'},
  {fr:'légume',en:'vegetable'},
  {fr:'fruit',en:'fruit'},
  {fr:'pomme',en:'apple'},
  {fr:'orange',en:'orange'},
  {fr:'banane',en:'banana'},
  {fr:'fraise',en:'strawberry'},
  {fr:'tomate',en:'tomato'},
  {fr:'pomme de terre',en:'potato'},
  {fr:'carotte',en:'carrot'},
  {fr:'oignon',en:'onion'},
  {fr:'ail',en:'garlic'},
  {fr:'sel',en:'salt'},
  {fr:'sucre',en:'sugar'},
  {fr:'beurre',en:'butter'},
  {fr:'huile',en:'oil'},
  {fr:'lait',en:'milk'},
  {fr:'thé',en:'tea'},
  {fr:'vin',en:'wine'},
  {fr:'bière',en:'beer'},
  {fr:'jus',en:'juice'},
  {fr:'gâteau',en:'cake'},
  {fr:'chocolat',en:'chocolate'},
  {fr:'bonbon',en:'candy'},
  {fr:'glace',en:'ice cream, ice'},
  {fr:'repas',en:'meal'},
  {fr:'petit déjeuner',en:'breakfast'},
  {fr:'déjeuner',en:'lunch'},
  {fr:'dîner',en:'dinner'},
  {fr:'recette',en:'recipe'},
  {fr:'assiette',en:'plate'},
  {fr:'couteau',en:'knife'},
  {fr:'fourchette',en:'fork'},
  {fr:'cuillère',en:'spoon'},
  {fr:'tasse',en:'cup'},
  {fr:'bouteille',en:'bottle'},
  {fr:'serviette',en:'napkin, towel'},
  {fr:'animal',en:'animal'},
  {fr:'chat',en:'cat'},
  {fr:'oiseau',en:'bird'},
  {fr:'cheval',en:'horse'},
  {fr:'cochon',en:'pig'},
  {fr:'vache',en:'cow'},
  {fr:'mouton',en:'sheep'},
  {fr:'lapin',en:'rabbit'},
  {fr:'poule',en:'hen'},
  {fr:'canard',en:'duck'},
  {fr:'serpent',en:'snake'},
  {fr:'souris',en:'mouse'},
  {fr:'loup',en:'wolf'},
  {fr:'lion',en:'lion'},
  {fr:'ours',en:'bear'},
  {fr:'singe',en:'monkey'},
  {fr:'éléphant',en:'elephant'},
  {fr:'tigre',en:'tiger'},
  {fr:'papillon',en:'butterfly'},
  {fr:'fourmi',en:'ant'},
  {fr:'abeille',en:'bee'},
  {fr:'araignée',en:'spider'},
  {fr:'arbre',en:'tree'},
  {fr:'fleur',en:'flower'},
  {fr:'herbe',en:'grass'},
  {fr:'feuille',en:'leaf'},
  {fr:'branche',en:'branch'},
  {fr:'racine',en:'root'},
  {fr:'graine',en:'seed'},
  {fr:'forêt',en:'forest'},
  {fr:'montagne',en:'mountain'},
  {fr:'rivière',en:'river'},
  {fr:'lac',en:'lake'},
  {fr:'mer',en:'sea'},
  {fr:'océan',en:'ocean'},
  {fr:'plage',en:'beach'},
  {fr:'île',en:'island'},
  {fr:'désert',en:'desert'},
  {fr:'colline',en:'hill'},
  {fr:'vallée',en:'valley'},
  {fr:'ciel',en:'sky'},
  {fr:'nuage',en:'cloud'},
  {fr:'pluie',en:'rain'},
  {fr:'neige',en:'snow'},
  {fr:'vent',en:'wind'},
  {fr:'soleil',en:'sun'},
  {fr:'lune',en:'moon'},
  {fr:'étoile',en:'star'},
  {fr:'orage',en:'storm'},
  {fr:'tonnerre',en:'thunder'},
  {fr:'éclair',en:'lightning'},
  {fr:'arc-en-ciel',en:'rainbow'},
  {fr:'chose',en:'thing'},
  {fr:'endroit',en:'place'},
  {fr:'début',en:'beginning'},
  {fr:'milieu',en:'middle'},
  {fr:'bout',en:'end, tip'},
  {fr:'forme',en:'shape, form'},
  {fr:'taille',en:'size'},
  {fr:'poids',en:'weight'},
  {fr:'couleur',en:'color'},
  {fr:'bruit',en:'noise, sound'},
  {fr:'lumière',en:'light'},
  {fr:'ombre',en:'shadow'},
  {fr:'chaleur',en:'heat'},
  {fr:'froid',en:'cold (noun)'},
  {fr:'odeur',en:'smell'},
  {fr:'goût',en:'taste'},
  {fr:'train',en:'train'},
  {fr:'avion',en:'airplane'},
  {fr:'bateau',en:'boat, ship'},
  {fr:'vélo',en:'bicycle'},
  {fr:'bus',en:'bus'},
  {fr:'camion',en:'truck'},
  {fr:'moto',en:'motorcycle'},
  {fr:'métro',en:'subway'},
  {fr:'gare',en:'train station'},
  {fr:'aéroport',en:'airport'},
  {fr:'pont',en:'bridge'},
  {fr:'magasin',en:'store, shop'},
  {fr:'marché',en:'market'},
  {fr:'restaurant',en:'restaurant'},
  {fr:'boulangerie',en:'bakery'},
  {fr:'pharmacie',en:'pharmacy'},
  {fr:'banque',en:'bank'},
  {fr:'église',en:'church'},
  {fr:'musée',en:'museum'},
  {fr:'cinéma',en:'cinema'},
  {fr:'théâtre',en:'theater'},
  {fr:'bibliothèque',en:'library'},
  {fr:'poste',en:'post office'},
  {fr:'parc',en:'park'},
  {fr:'piscine',en:'swimming pool'},
  {fr:'stade',en:'stadium'},
  {fr:'usine',en:'factory'},
  {fr:'ferme',en:'farm'},
  {fr:'château',en:'castle'},
  {fr:'palais',en:'palace'},
  {fr:'tour',en:'tower'},
  {fr:'prison',en:'prison'},
  {fr:'université',en:'university'},
  {fr:'dollar',en:'dollar'},
  {fr:'euro',en:'euro'},
  {fr:'pièce',en:'coin, room'},
  {fr:'billet',en:'ticket, banknote'},
  {fr:'compte',en:'account'},
  {fr:'dette',en:'debt'},
  {fr:'impôt',en:'tax'},
  {fr:'emploi',en:'job, employment'},
  {fr:'salaire',en:'salary'},
  {fr:'projet',en:'project'},
  {fr:'entreprise',en:'business, company'},
  {fr:'industrie',en:'industry'},
  {fr:'commerce',en:'trade, business'},
  {fr:'produit',en:'product'},
  {fr:'machine',en:'machine'},
  {fr:'outil',en:'tool'},
  {fr:'papier',en:'paper'},
  {fr:'crayon',en:'pencil'},
  {fr:'stylo',en:'pen'},
  {fr:'cahier',en:'notebook'},
  {fr:'page',en:'page'},
  {fr:'journal',en:'newspaper'},
  {fr:'magazine',en:'magazine'},
  {fr:'article',en:'article'},
  {fr:'annonce',en:'announcement, ad'},
  {fr:'affiche',en:'poster'},
  {fr:'programme',en:'program'},
  {fr:'idée',en:'idea'},
  {fr:'pensée',en:'thought'},
  {fr:'opinion',en:'opinion'},
  {fr:'problème',en:'problem'},
  {fr:'solution',en:'solution'},
  {fr:'réponse',en:'answer'},
  {fr:'exemple',en:'example'},
  {fr:'preuve',en:'proof, evidence'},
  {fr:'résultat',en:'result'},
  {fr:'succès',en:'success'},
  {fr:'échec',en:'failure'},
  {fr:'erreur',en:'error, mistake'},
  {fr:'danger',en:'danger'},
  {fr:'accident',en:'accident'},
  {fr:'chance',en:'luck, chance'},
  {fr:'surprise',en:'surprise'},
  {fr:'plaisir',en:'pleasure'},
  {fr:'douleur',en:'pain'},
  {fr:'bonheur',en:'happiness'},
  {fr:'tristesse',en:'sadness'},
  {fr:'colère',en:'anger'},
  {fr:'joie',en:'joy'},
  {fr:'amour',en:'love'},
  {fr:'haine',en:'hatred'},
  {fr:'confiance',en:'trust'},
  {fr:'respect',en:'respect'},
  {fr:'liberté',en:'freedom'},
  {fr:'paix',en:'peace'},
  {fr:'vérité',en:'truth'},
  {fr:'mensonge',en:'lie'},
  {fr:'rêve',en:'dream'},
  {fr:'espoir',en:'hope'},
  {fr:'souhait',en:'wish'},
  {fr:'promesse',en:'promise'},
  {fr:'excuse',en:'excuse'},
  {fr:'pardon',en:'forgiveness'},
  {fr:'cadeau',en:'gift'},
  {fr:'anniversaire',en:'birthday'},
  {fr:'fête',en:'party, celebration'},
  {fr:'mariage',en:'wedding'},
  {fr:'vacances',en:'vacation'},
  {fr:'week-end',en:'weekend'},
  {fr:'congé',en:'day off, leave'},
  {fr:'rendez-vous',en:'appointment'},
  {fr:'réunion',en:'meeting'},
  {fr:'cérémonie',en:'ceremony'},
  {fr:'spectacle',en:'show'},
  {fr:'concert',en:'concert'},
  {fr:'exposition',en:'exhibition'},
  {fr:'match',en:'match, game'},
  {fr:'compétition',en:'competition'},
  {fr:'course',en:'race, errand'},
  {fr:'promenade',en:'walk, stroll'},
  {fr:'balade',en:'stroll'},
  {fr:'aventure',en:'adventure'},
  {fr:'expérience',en:'experience'},
  {fr:'habitude',en:'habit'},
  {fr:'règle',en:'rule'},
  {fr:'loi',en:'law'},
  {fr:'gouvernement',en:'government'},
  {fr:'politique',en:'politics, policy'},
  {fr:'élection',en:'election'},
  {fr:'droits',en:'rights'},
  {fr:'justice',en:'justice'},
  {fr:'tribunal',en:'court'},
  {fr:'santé',en:'health'},
  {fr:'maladie',en:'illness, disease'},
  {fr:'médecin',en:'doctor'},
  {fr:'médicament',en:'medicine, drug'},
  {fr:'traitement',en:'treatment'},
  {fr:'opération',en:'operation'},
  {fr:'fièvre',en:'fever'},
  {fr:'blessure',en:'injury, wound'},
  {fr:'cicatrice',en:'scar'},
  {fr:'mauvais',en:'bad'},
  {fr:'joli',en:'pretty'},
  {fr:'laid',en:'ugly'},
  {fr:'vieux',en:'old'},
  {fr:'ancien',en:'old, ancient, former'},
  {fr:'moderne',en:'modern'},
  {fr:'simple',en:'simple'},
  {fr:'facile',en:'easy'},
  {fr:'difficile',en:'difficult'},
  {fr:'dur',en:'hard, tough'},
  {fr:'doux',en:'soft, sweet, gentle'},
  {fr:'léger',en:'light (weight)'},
  {fr:'lourd',en:'heavy'},
  {fr:'rapide',en:'fast'},
  {fr:'lent',en:'slow'},
  {fr:'chaud',en:'hot, warm'},
  {fr:'sec',en:'dry'},
  {fr:'mouillé',en:'wet'},
  {fr:'propre',en:'clean, own'},
  {fr:'sale',en:'dirty'},
  {fr:'plein',en:'full'},
  {fr:'vide',en:'empty'},
  {fr:'ouvert',en:'open'},
  {fr:'fermé',en:'closed'},
  {fr:'large',en:'wide'},
  {fr:'étroit',en:'narrow'},
  {fr:'épais',en:'thick'},
  {fr:'mince',en:'thin'},
  {fr:'profond',en:'deep'},
  {fr:'heureux',en:'happy'},
  {fr:'triste',en:'sad'},
  {fr:'content',en:'happy, pleased'},
  {fr:'fâché',en:'angry'},
  {fr:'inquiet',en:'worried'},
  {fr:'surpris',en:'surprised'},
  {fr:'fatigué',en:'tired'},
  {fr:'malade',en:'sick'},
  {fr:'vivant',en:'alive'},
  {fr:'riche',en:'rich'},
  {fr:'pauvre',en:'poor'},
  {fr:'cher',en:'expensive, dear'},
  {fr:'gratuit',en:'free (no cost)'},
  {fr:'important',en:'important'},
  {fr:'nécessaire',en:'necessary'},
  {fr:'possible',en:'possible'},
  {fr:'impossible',en:'impossible'},
  {fr:'certain',en:'certain, sure'},
  {fr:'sûr',en:'sure, safe'},
  {fr:'faux',en:'false, fake'},
  {fr:'normal',en:'normal'},
  {fr:'bizarre',en:'strange, weird'},
  {fr:'drôle',en:'funny'},
  {fr:'sérieux',en:'serious'},
  {fr:'gentil',en:'kind, nice'},
  {fr:'méchant',en:'mean, naughty'},
  {fr:'poli',en:'polite'},
  {fr:'intelligent',en:'intelligent'},
  {fr:'stupide',en:'stupid'},
  {fr:'fou',en:'crazy'},
  {fr:'brave',en:'brave'},
  {fr:'courageux',en:'courageous'},
  {fr:'timide',en:'shy'},
  {fr:'calme',en:'calm'},
  {fr:'nerveux',en:'nervous'},
  {fr:'curieux',en:'curious'},
  {fr:'jaloux',en:'jealous'},
  {fr:'fier',en:'proud'},
  {fr:'ensemble',en:'together'},
  {fr:'prochain',en:'next'},
  {fr:'deuxième',en:'second'},
  {fr:'troisième',en:'third'},
  {fr:'rouge',en:'red'},
  {fr:'bleu',en:'blue'},
  {fr:'vert',en:'green'},
  {fr:'jaune',en:'yellow'},
  {fr:'blanc',en:'white'},
  {fr:'gris',en:'gray'},
  {fr:'rose',en:'pink'},
  {fr:'marron',en:'brown'},
  {fr:'violet',en:'purple'},
  {fr:'clair',en:'clear, light'},
  {fr:'foncé',en:'dark (color)'},
  {fr:'sombre',en:'dark, gloomy'},
  {fr:'brillant',en:'brilliant, shiny'},
  {fr:'souvent',en:'often'},
  {fr:'parfois',en:'sometimes'},
  {fr:'rarement',en:'rarely'},
  {fr:'déjà',en:'already'},
  {fr:'bientôt',en:'soon'},
  {fr:'aujourd\'hui',en:'today'},
  {fr:'demain',en:'tomorrow'},
  {fr:'hier',en:'yesterday'},
  {fr:'tôt',en:'early'},
  {fr:'tard',en:'late'},
  {fr:'vite',en:'quickly, fast'},
  {fr:'lentement',en:'slowly'},
  {fr:'doucement',en:'gently, softly'},
  {fr:'soudain',en:'suddenly'},
  {fr:'seulement',en:'only'},
  {fr:'exactement',en:'exactly'},
  {fr:'probablement',en:'probably'},
  {fr:'certainement',en:'certainly'},
  {fr:'peut-être',en:'maybe, perhaps'},
  {fr:'bien sûr',en:'of course'},
  {fr:'environ',en:'about, approximately'},
  {fr:'presque',en:'almost'},
  {fr:'assez',en:'enough, quite'},
  {fr:'beaucoup',en:'a lot, much'},
  {fr:'plutôt',en:'rather'},
  {fr:'surtout',en:'especially, above all'},
  {fr:'d\'abord',en:'first of all'},
  {fr:'ensuite',en:'then, next'},
  {fr:'enfin',en:'finally'},
  {fr:'puis',en:'then'},
  {fr:'cependant',en:'however'},
  {fr:'pourtant',en:'yet, however'},
  {fr:'quand même',en:'still, anyway'},
  {fr:'sinon',en:'otherwise'},
  {fr:'autrement',en:'otherwise'},
  {fr:'en fait',en:'in fact, actually'},
  {fr:'en effet',en:'indeed'},
  {fr:'par exemple',en:'for example'},
  {fr:'c\'est-à-dire',en:'that is to say'},
  {fr:'à cause de',en:'because of'},
  {fr:'grâce à',en:'thanks to'},
  {fr:'au lieu de',en:'instead of'},
  {fr:'malgré',en:'despite'},
  {fr:'pendant',en:'during'},
  {fr:'depuis',en:'since, for (time)'},
  {fr:'jusqu\'à',en:'until'},
  {fr:'vers',en:'toward'},
  {fr:'contre',en:'against'},
  {fr:'parmi',en:'among'},
  {fr:'selon',en:'according to'},
  {fr:'à travers',en:'through, across'},
  {fr:'au-dessus',en:'above'},
  {fr:'au-dessous',en:'below'},
  {fr:'devant',en:'in front of'},
  {fr:'derrière',en:'behind'},
  {fr:'à côté de',en:'next to'},
  {fr:'loin de',en:'far from'},
  {fr:'près de',en:'near'},
  {fr:'autour de',en:'around'},
  {fr:'chez',en:'at (someone\'s place)'},
  {fr:'chemise',en:'shirt'},
  {fr:'pantalon',en:'pants'},
  {fr:'robe',en:'dress'},
  {fr:'jupe',en:'skirt'},
  {fr:'manteau',en:'coat'},
  {fr:'veste',en:'jacket'},
  {fr:'chaussure',en:'shoe'},
  {fr:'chapeau',en:'hat'},
  {fr:'ceinture',en:'belt'},
  {fr:'lunettes',en:'glasses'},
  {fr:'bijou',en:'jewel'},
  {fr:'bague',en:'ring'},
  {fr:'collier',en:'necklace'},
  {fr:'montre',en:'watch'},
  {fr:'parapluie',en:'umbrella'},
  {fr:'portefeuille',en:'wallet'},
  {fr:'ordinateur',en:'computer'},
  {fr:'écran',en:'screen'},
  {fr:'clavier',en:'keyboard'},
  {fr:'internet',en:'internet'},
  {fr:'message',en:'message'},
  {fr:'adresse',en:'address'},
  {fr:'timbre',en:'stamp'},
  {fr:'enveloppe',en:'envelope'},
  {fr:'colis',en:'package'},
  {fr:'facteur',en:'mailman'},
  {fr:'numéro',en:'number'},
  {fr:'chiffre',en:'digit, figure'},
  {fr:'moitié',en:'half'},
  {fr:'quart',en:'quarter'},
  {fr:'double',en:'double'},
  {fr:'dizaine',en:'about ten'},
  {fr:'centaine',en:'about a hundred'},
  {fr:'millier',en:'about a thousand'},
  {fr:'million',en:'million'},
  {fr:'zéro',en:'zero'},
  {fr:'quatre',en:'four'},
  {fr:'cinq',en:'five'},
  {fr:'six',en:'six'},
  {fr:'sept',en:'seven'},
  {fr:'huit',en:'eight'},
  {fr:'neuf',en:'nine'},
  {fr:'dix',en:'ten'},
  {fr:'onze',en:'eleven'},
  {fr:'douze',en:'twelve'},
  {fr:'treize',en:'thirteen'},
  {fr:'quatorze',en:'fourteen'},
  {fr:'quinze',en:'fifteen'},
  {fr:'seize',en:'sixteen'},
  {fr:'vingt',en:'twenty'},
  {fr:'trente',en:'thirty'},
  {fr:'quarante',en:'forty'},
  {fr:'cinquante',en:'fifty'},
  {fr:'soixante',en:'sixty'},
  {fr:'cent',en:'hundred'},
  {fr:'mille',en:'thousand'},
  {fr:'lundi',en:'Monday'},
  {fr:'mardi',en:'Tuesday'},
  {fr:'mercredi',en:'Wednesday'},
  {fr:'jeudi',en:'Thursday'},
  {fr:'vendredi',en:'Friday'},
  {fr:'samedi',en:'Saturday'},
  {fr:'dimanche',en:'Sunday'},
  {fr:'janvier',en:'January'},
  {fr:'février',en:'February'},
  {fr:'mars',en:'March'},
  {fr:'avril',en:'April'},
  {fr:'mai',en:'May'},
  {fr:'juin',en:'June'},
  {fr:'juillet',en:'July'},
  {fr:'août',en:'August'},
  {fr:'septembre',en:'September'},
  {fr:'octobre',en:'October'},
  {fr:'novembre',en:'November'},
  {fr:'décembre',en:'December'},
  {fr:'printemps',en:'spring'},
  {fr:'été',en:'summer'},
  {fr:'automne',en:'autumn, fall'},
  {fr:'hiver',en:'winter'},
  {fr:'siècle',en:'century'},
  {fr:'seconde',en:'second (time)'},
  {fr:'instant',en:'instant, moment'},
  {fr:'période',en:'period'},
  {fr:'durée',en:'duration'},
  {fr:'avenir',en:'future'},
  {fr:'passé',en:'past'},
  {fr:'présent',en:'present'},
  {fr:'direction',en:'direction'},
  {fr:'nord',en:'north'},
  {fr:'sud',en:'south'},
  {fr:'ouest',en:'west'},
  {fr:'gauche',en:'left'},
  {fr:'droite',en:'right'},
  {fr:'coin',en:'corner'},
  {fr:'centre',en:'center'},
  {fr:'bord',en:'edge'},
  {fr:'distance',en:'distance'},
  {fr:'kilomètre',en:'kilometer'},
  {fr:'mètre',en:'meter'},
  {fr:'centimètre',en:'centimeter'},
  {fr:'hauteur',en:'height'},
  {fr:'largeur',en:'width'},
  {fr:'longueur',en:'length'},
  {fr:'surface',en:'surface'},
  {fr:'espace',en:'space'},
  {fr:'région',en:'region'},
  {fr:'département',en:'department'},
  {fr:'capitale',en:'capital'},
  {fr:'frontière',en:'border'},
  {fr:'passeport',en:'passport'},
  {fr:'valise',en:'suitcase'},
  {fr:'réservation',en:'reservation'},
  {fr:'hôtel',en:'hotel'},
  {fr:'étage',en:'floor (level)'},
  {fr:'ascenseur',en:'elevator'},
  {fr:'sortie',en:'exit'},
  {fr:'entrée',en:'entrance'},
  {fr:'arrivée',en:'arrival'},
  {fr:'départ',en:'departure'},
  {fr:'retour',en:'return'},
  {fr:'retard',en:'delay'},
  {fr:'horaire',en:'schedule'},
  {fr:'guichet',en:'counter, ticket window'},
  {fr:'bagages',en:'luggage'},
  {fr:'plan',en:'plan, map'},
  {fr:'guide',en:'guide'},
  {fr:'touriste',en:'tourist'},
  {fr:'monument',en:'monument'},
  {fr:'cathédrale',en:'cathedral'},
  {fr:'fontaine',en:'fountain'},
  {fr:'statue',en:'statue'},
  {fr:'fleuve',en:'large river'},
  {fr:'côte',en:'coast'},
  {fr:'campagne',en:'countryside'},
  {fr:'village',en:'village'},
  {fr:'quartier',en:'neighborhood'},
  {fr:'banlieue',en:'suburb'},
  {fr:'trottoir',en:'sidewalk'},
  {fr:'carrefour',en:'crossroads'},
  {fr:'panneau',en:'sign (road)'},
  {fr:'permis',en:'permit, license'},
  {fr:'essence',en:'gasoline'},
  {fr:'pneu',en:'tire'},
  {fr:'moteur',en:'engine'},
  {fr:'vitesse',en:'speed'},
  {fr:'circulation',en:'traffic'},
  {fr:'embouteillage',en:'traffic jam'},
  {fr:'piéton',en:'pedestrian'},
  {fr:'conducteur',en:'driver'},
  {fr:'passager',en:'passenger'},
  {fr:'science',en:'science'},
  {fr:'mathématiques',en:'mathematics'},
  {fr:'physique',en:'physics'},
  {fr:'chimie',en:'chemistry'},
  {fr:'biologie',en:'biology'},
  {fr:'géographie',en:'geography'},
  {fr:'informatique',en:'computer science'},
  {fr:'grammaire',en:'grammar'},
  {fr:'vocabulaire',en:'vocabulary'},
  {fr:'phrase',en:'sentence'},
  {fr:'paragraphe',en:'paragraph'},
  {fr:'texte',en:'text'},
  {fr:'poème',en:'poem'},
  {fr:'roman',en:'novel'},
  {fr:'auteur',en:'author'},
  {fr:'écrivain',en:'writer'},
  {fr:'poète',en:'poet'},
  {fr:'artiste',en:'artist'},
  {fr:'musicien',en:'musician'},
  {fr:'chanteur',en:'singer'},
  {fr:'acteur',en:'actor'},
  {fr:'peintre',en:'painter'},
  {fr:'sculpteur',en:'sculptor'},
  {fr:'architecte',en:'architect'},
  {fr:'ingénieur',en:'engineer'},
  {fr:'chercheur',en:'researcher'},
  {fr:'scientifique',en:'scientist'},
  {fr:'journaliste',en:'journalist'},
  {fr:'photographe',en:'photographer'},
  {fr:'directeur',en:'director'},
  {fr:'employé',en:'employee'},
  {fr:'ouvrier',en:'worker'},
  {fr:'agriculteur',en:'farmer'},
  {fr:'boulanger',en:'baker'},
  {fr:'boucher',en:'butcher'},
  {fr:'coiffeur',en:'hairdresser'},
  {fr:'plombier',en:'plumber'},
  {fr:'électricien',en:'electrician'},
  {fr:'pompier',en:'firefighter'},
  {fr:'policier',en:'police officer'},
  {fr:'infirmier',en:'nurse'},
  {fr:'dentiste',en:'dentist'},
  {fr:'vétérinaire',en:'veterinarian'},
  {fr:'pilote',en:'pilot'},
  {fr:'chauffeur',en:'driver'},
  {fr:'cuisinier',en:'cook'},
  {fr:'serveur',en:'waiter'},
  {fr:'vendeur',en:'salesperson'},
  {fr:'comptable',en:'accountant'},
  {fr:'contrat',en:'contract'},
  {fr:'facture',en:'invoice, bill'},
  {fr:'budget',en:'budget'},
  {fr:'bénéfice',en:'profit'},
  {fr:'perte',en:'loss'},
  {fr:'publicité',en:'advertising'},
  {fr:'marque',en:'brand'},
  {fr:'qualité',en:'quality'},
  {fr:'quantité',en:'quantity'},
  {fr:'mémoire',en:'memory'},
  {fr:'intelligence',en:'intelligence'},
  {fr:'connaissance',en:'knowledge'},
  {fr:'éducation',en:'education'},
  {fr:'diplôme',en:'diploma, degree'},
  {fr:'examen',en:'exam'},
  {fr:'note',en:'grade, note'},
  {fr:'leçon',en:'lesson'},
  {fr:'exercice',en:'exercise'},
  {fr:'recherche',en:'research'},
  {fr:'découverte',en:'discovery'},
  {fr:'invention',en:'invention'},
  {fr:'technologie',en:'technology'},
  {fr:'progrès',en:'progress'},
  {fr:'changement',en:'change'},
  {fr:'développement',en:'development'},
  {fr:'amélioration',en:'improvement'},
  {fr:'évolution',en:'evolution'},
  {fr:'révolution',en:'revolution'},
  {fr:'tradition',en:'tradition'},
  {fr:'culture',en:'culture'},
  {fr:'religion',en:'religion'},
  {fr:'philosophie',en:'philosophy'},
  {fr:'art',en:'art'},
  {fr:'littérature',en:'literature'},
  {fr:'peinture',en:'painting'},
  {fr:'sculpture',en:'sculpture'},
  {fr:'danse',en:'dance'},
  {fr:'photographie',en:'photography'},
  {fr:'sport',en:'sport'},
  {fr:'football',en:'soccer'},
  {fr:'tennis',en:'tennis'},
  {fr:'natation',en:'swimming'},
  {fr:'gymnastique',en:'gymnastics'},
  {fr:'athlétisme',en:'athletics'},
  {fr:'ski',en:'skiing'},
  {fr:'randonnée',en:'hiking'},
  {fr:'escalade',en:'climbing'},
  {fr:'équitation',en:'horse riding'},
  {fr:'pêche',en:'fishing'},
  {fr:'chasse',en:'hunting'},
  {fr:'camping',en:'camping'},
  {fr:'plante',en:'plant'},
  {fr:'tulipe',en:'tulip'},
  {fr:'marguerite',en:'daisy'},
  {fr:'pierre',en:'stone'},
  {fr:'rocher',en:'rock'},
  {fr:'sable',en:'sand'},
  {fr:'boue',en:'mud'},
  {fr:'poussière',en:'dust'},
  {fr:'fumée',en:'smoke'},
  {fr:'flamme',en:'flame'},
  {fr:'cendre',en:'ash'},
  {fr:'métal',en:'metal'},
  {fr:'fer',en:'iron'},
  {fr:'acier',en:'steel'},
  {fr:'or',en:'gold'},
  {fr:'cuivre',en:'copper'},
  {fr:'bois',en:'wood'},
  {fr:'tissu',en:'fabric'},
  {fr:'cuir',en:'leather'},
  {fr:'coton',en:'cotton'},
  {fr:'laine',en:'wool'},
  {fr:'soie',en:'silk'},
  {fr:'plastique',en:'plastic'},
  {fr:'caoutchouc',en:'rubber'},
  {fr:'fil',en:'thread, wire'},
  {fr:'corde',en:'rope'},
  {fr:'chaîne',en:'chain'},
  {fr:'noeud',en:'knot'},
  {fr:'trou',en:'hole'},
  {fr:'fente',en:'crack, slot'},
  {fr:'angle',en:'angle'},
  {fr:'cercle',en:'circle'},
  {fr:'carré',en:'square'},
  {fr:'triangle',en:'triangle'},
  {fr:'ligne',en:'line'},
  {fr:'courbe',en:'curve'},
  {fr:'sommet',en:'top, summit'},
  {fr:'fond',en:'bottom, background'},
  {fr:'silence',en:'silence'},
  {fr:'victoire',en:'victory'},
  {fr:'défaite',en:'defeat'},
  {fr:'autorité',en:'authority'},
  {fr:'influence',en:'influence'},
  {fr:'responsabilité',en:'responsibility'},
  {fr:'obligation',en:'obligation'},
  {fr:'permission',en:'permission'},
  {fr:'interdiction',en:'prohibition'},
  {fr:'récompense',en:'reward'},
  {fr:'punition',en:'punishment'},
  {fr:'avantage',en:'advantage'},
  {fr:'inconvénient',en:'disadvantage'},
  {fr:'différence',en:'difference'},
  {fr:'ressemblance',en:'resemblance'},
  {fr:'comparaison',en:'comparison'},
  {fr:'choix',en:'choice'},
  {fr:'décision',en:'decision'},
  {fr:'conséquence',en:'consequence'},
  {fr:'cause',en:'cause'},
  {fr:'effet',en:'effect'},
  {fr:'but',en:'goal, purpose'},
  {fr:'intention',en:'intention'},
  {fr:'effort',en:'effort'},
  {fr:'tentative',en:'attempt'},
  {fr:'réussite',en:'success'},
  {fr:'recul',en:'setback'},
  {fr:'étape',en:'step, stage'},
  {fr:'processus',en:'process'},
  {fr:'méthode',en:'method'},
  {fr:'système',en:'system'},
  {fr:'structure',en:'structure'},
  {fr:'organisation',en:'organization'},
  {fr:'stratégie',en:'strategy'},
  {fr:'tactique',en:'tactic'},
  {fr:'situation',en:'situation'},
  {fr:'condition',en:'condition'},
  {fr:'circonstance',en:'circumstance'},
  {fr:'occasion',en:'occasion, opportunity'},
  {fr:'possibilité',en:'possibility'},
  {fr:'opportunité',en:'opportunity'},
  {fr:'difficulté',en:'difficulty'},
  {fr:'obstacle',en:'obstacle'},
  {fr:'défi',en:'challenge'},
  {fr:'risque',en:'risk'},
  {fr:'sécurité',en:'safety, security'},
  {fr:'protection',en:'protection'},
  {fr:'défense',en:'defense'},
  {fr:'attaque',en:'attack'},
  {fr:'conflit',en:'conflict'},
  {fr:'accord',en:'agreement'},
  {fr:'négociation',en:'negotiation'},
  {fr:'compromis',en:'compromise'},
  {fr:'discussion',en:'discussion'},
  {fr:'conversation',en:'conversation'},
  {fr:'débat',en:'debate'},
  {fr:'argument',en:'argument'},
  {fr:'critique',en:'criticism'},
  {fr:'compliment',en:'compliment'},
  {fr:'conseil',en:'advice'},
  {fr:'avertissement',en:'warning'},
  {fr:'invitation',en:'invitation'},
  {fr:'annulation',en:'cancellation'},
  {fr:'confirmation',en:'confirmation'},
  {fr:'explication',en:'explanation'},
  {fr:'description',en:'description'},
  {fr:'information',en:'information'},
  {fr:'rumeur',en:'rumor'},
  {fr:'mystère',en:'mystery'},
  {fr:'miracle',en:'miracle'},
  {fr:'catastrophe',en:'catastrophe'},
  {fr:'tragédie',en:'tragedy'},
  {fr:'comédie',en:'comedy'},
  {fr:'ironie',en:'irony'},
  {fr:'humour',en:'humor'},
  {fr:'blague',en:'joke'},
  {fr:'sourire',en:'smile'},
  {fr:'larme',en:'tear'},
  {fr:'cri',en:'scream, cry'},
  {fr:'murmure',en:'whisper'},
  {fr:'soupir',en:'sigh'},
  {fr:'souffle',en:'breath'},
  {fr:'regard',en:'look, gaze'},
  {fr:'geste',en:'gesture'},
  {fr:'signal',en:'signal'},
  {fr:'signe',en:'sign'},
  {fr:'symbole',en:'symbol'},
  {fr:'image',en:'image'},
  {fr:'modèle',en:'model, pattern'},
  {fr:'s\'il vous plaît',en:'please (formal)'},
  {fr:'s\'il te plaît',en:'please (informal)'},
  {fr:'excusez-moi',en:'excuse me'},
  {fr:'je suis désolé',en:'I am sorry'},
  {fr:'comment allez-vous',en:'how are you (formal)'},
  {fr:'comment vas-tu',en:'how are you (informal)'},
  {fr:'je ne comprends pas',en:'I don\'t understand'},
  {fr:'parlez-vous anglais',en:'do you speak English'},
  {fr:'je voudrais',en:'I would like'},
  {fr:'combien ça coûte',en:'how much does it cost'},
  {fr:'où sont les toilettes',en:'where are the toilets'},
  {fr:'à bientôt',en:'see you soon'},
  {fr:'à demain',en:'see you tomorrow'},
  {fr:'bonne nuit',en:'good night'},
  {fr:'bonne journée',en:'have a nice day'},
  {fr:'bon appétit',en:'enjoy your meal'},
  {fr:'bienvenue',en:'welcome'},
  {fr:'félicitations',en:'congratulations'},
  {fr:'bonne chance',en:'good luck'},
  {fr:'au secours',en:'help!'},
  {fr:'attention',en:'watch out'},
  {fr:'d\'accord',en:'okay, agreed'},
  {fr:'pas du tout',en:'not at all'},
  {fr:'tout à fait',en:'absolutely'},
  {fr:'n\'importe quoi',en:'anything, nonsense'},
  {fr:'tant pis',en:'too bad'},
  {fr:'tant mieux',en:'so much the better'},
  {fr:'en tout cas',en:'in any case'},
  {fr:'de rien',en:'you\'re welcome'},
  {fr:'je t\'en prie',en:'you\'re welcome (informal)'},
  {fr:'agréable',en:'pleasant'},
  {fr:'désagréable',en:'unpleasant'},
  {fr:'confortable',en:'comfortable'},
  {fr:'inconfortable',en:'uncomfortable'},
  {fr:'utile',en:'useful'},
  {fr:'inutile',en:'useless'},
  {fr:'intéressant',en:'interesting'},
  {fr:'ennuyeux',en:'boring'},
  {fr:'amusant',en:'amusing, funny'},
  {fr:'passionnant',en:'exciting, fascinating'},
  {fr:'effrayant',en:'scary'},
  {fr:'magnifique',en:'magnificent'},
  {fr:'merveilleux',en:'wonderful'},
  {fr:'excellent',en:'excellent'},
  {fr:'terrible',en:'terrible'},
  {fr:'horrible',en:'horrible'},
  {fr:'affreux',en:'awful'},
  {fr:'formidable',en:'tremendous, great'},
  {fr:'remarquable',en:'remarkable'},
  {fr:'ordinaire',en:'ordinary'},
  {fr:'spécial',en:'special'},
  {fr:'unique',en:'unique'},
  {fr:'rare',en:'rare'},
  {fr:'commun',en:'common'},
  {fr:'particulier',en:'particular'},
  {fr:'principal',en:'main, principal'},
  {fr:'secondaire',en:'secondary'},
  {fr:'supplémentaire',en:'additional'},
  {fr:'suffisant',en:'sufficient'},
  {fr:'insuffisant',en:'insufficient'},
  {fr:'complet',en:'complete'},
  {fr:'incomplet',en:'incomplete'},
  {fr:'correct',en:'correct'},
  {fr:'incorrect',en:'incorrect'},
  {fr:'parfait',en:'perfect'},
  {fr:'imparfait',en:'imperfect'},
  {fr:'exact',en:'exact'},
  {fr:'approximatif',en:'approximate'},
  {fr:'précis',en:'precise'},
  {fr:'vague',en:'vague'},
  {fr:'évident',en:'obvious'},
  {fr:'probable',en:'probable'},
  {fr:'improbable',en:'improbable'},
  {fr:'capable',en:'capable'},
  {fr:'incapable',en:'incapable'},
  {fr:'responsable',en:'responsible'},
  {fr:'disponible',en:'available'},
  {fr:'absent',en:'absent'},
  {fr:'permanent',en:'permanent'},
  {fr:'temporaire',en:'temporary'},
  {fr:'régulier',en:'regular'},
  {fr:'irrégulier',en:'irregular'},
  {fr:'constant',en:'constant'},
  {fr:'variable',en:'variable'},
  {fr:'stable',en:'stable'},
  {fr:'fragile',en:'fragile'},
  {fr:'solide',en:'solid'},
  {fr:'liquide',en:'liquid'},
  {fr:'naturel',en:'natural'},
  {fr:'artificiel',en:'artificial'},
  {fr:'automatique',en:'automatic'},
  {fr:'manuel',en:'manual'},
  {fr:'public',en:'public'},
  {fr:'privé',en:'private'},
  {fr:'officiel',en:'official'},
  {fr:'personnel',en:'personal'},
  {fr:'professionnel',en:'professional'},
  {fr:'national',en:'national'},
  {fr:'international',en:'international'},
  {fr:'local',en:'local'},
  {fr:'mondial',en:'global, worldwide'},
  {fr:'humain',en:'human'},
  {fr:'végétal',en:'plant (adj.)'},
  {fr:'minéral',en:'mineral'},
  {fr:'abandonner',en:'to abandon'},
  {fr:'accompagner',en:'to accompany'},
  {fr:'accrocher',en:'to hang, to hook'},
  {fr:'admettre',en:'to admit'},
  {fr:'adopter',en:'to adopt'},
  {fr:'affirmer',en:'to affirm'},
  {fr:'agir',en:'to act'},
  {fr:'ajouter',en:'to add'},
  {fr:'allumer',en:'to light, to turn on'},
  {fr:'annoncer',en:'to announce'},
  {fr:'apercevoir',en:'to notice, to catch sight of'},
  {fr:'appuyer',en:'to press, to lean'},
  {fr:'assurer',en:'to assure, to insure'},
  {fr:'attacher',en:'to attach, to tie'},
  {fr:'attraper',en:'to catch'},
  {fr:'augmenter',en:'to increase'},
  {fr:'baisser',en:'to lower'},
  {fr:'bloquer',en:'to block'},
  {fr:'bouger',en:'to move'},
  {fr:'briller',en:'to shine'},
  {fr:'calculer',en:'to calculate'},
  {fr:'célébrer',en:'to celebrate'},
  {fr:'charger',en:'to load, to charge'},
  {fr:'chasser',en:'to hunt, to chase'},
  {fr:'chauffer',en:'to heat'},
  {fr:'coller',en:'to glue, to stick'},
  {fr:'commander',en:'to order'},
  {fr:'communiquer',en:'to communicate'},
  {fr:'comparer',en:'to compare'},
  {fr:'compléter',en:'to complete'},
  {fr:'composer',en:'to compose'},
  {fr:'concentrer',en:'to concentrate'},
  {fr:'confondre',en:'to confuse'},
  {fr:'conseiller',en:'to advise'},
  {fr:'conserver',en:'to preserve'},
  {fr:'consommer',en:'to consume'},
  {fr:'contenir',en:'to contain'},
  {fr:'contrôler',en:'to control'},
  {fr:'convaincre',en:'to convince'},
  {fr:'corriger',en:'to correct'},
  {fr:'décevoir',en:'to disappoint'},
  {fr:'déclarer',en:'to declare'},
  {fr:'décorer',en:'to decorate'},
  {fr:'découvrir',en:'to discover'},
  {fr:'défendre',en:'to defend'},
  {fr:'déranger',en:'to disturb'},
  {fr:'désirer',en:'to desire'},
  {fr:'détruire',en:'to destroy'},
  {fr:'deviner',en:'to guess'},
  {fr:'diminuer',en:'to decrease'},
  {fr:'diriger',en:'to direct, to manage'},
  {fr:'discuter',en:'to discuss'},
  {fr:'disparaître',en:'to disappear'},
  {fr:'distribuer',en:'to distribute'},
  {fr:'diviser',en:'to divide'},
  {fr:'dominer',en:'to dominate'},
  {fr:'échapper',en:'to escape'},
  {fr:'éclairer',en:'to light up'},
  {fr:'économiser',en:'to save (money)'},
  {fr:'effacer',en:'to erase'},
  {fr:'effrayer',en:'to frighten'},
  {fr:'élever',en:'to raise'},
  {fr:'éliminer',en:'to eliminate'},
  {fr:'embrasser',en:'to kiss, to embrace'},
  {fr:'émettre',en:'to emit'},
  {fr:'émouvoir',en:'to move (emotionally)'},
  {fr:'encourager',en:'to encourage'},
  {fr:'endommager',en:'to damage'},
  {fr:'enlever',en:'to remove'},
  {fr:'enrichir',en:'to enrich'},
  {fr:'entourer',en:'to surround'},
  {fr:'entraîner',en:'to train, to drag'},
  {fr:'épouser',en:'to marry'},
  {fr:'équiper',en:'to equip'},
  {fr:'établir',en:'to establish'},
  {fr:'éteindre',en:'to extinguish, to turn off'},
  {fr:'étonner',en:'to surprise'},
  {fr:'évaluer',en:'to evaluate'},
  {fr:'éviter',en:'to avoid'},
  {fr:'examiner',en:'to examine'},
  {fr:'excuser',en:'to excuse'},
  {fr:'exiger',en:'to demand'},
  {fr:'fabriquer',en:'to manufacture'},
  {fr:'fixer',en:'to fix, to set'},
  {fr:'fonctionner',en:'to function, to work'},
  {fr:'fournir',en:'to supply'},
  {fr:'franchir',en:'to cross, to overcome'},
  {fr:'frapper',en:'to hit, to knock'},
  {fr:'glisser',en:'to slip, to slide'},
  {fr:'goûter',en:'to taste'},
  {fr:'guérir',en:'to heal, to cure'},
  {fr:'habiter',en:'to live (in a place)'},
  {fr:'hésiter',en:'to hesitate'},
  {fr:'identifier',en:'to identify'},
  {fr:'ignorer',en:'to ignore'},
  {fr:'illustrer',en:'to illustrate'},
  {fr:'imposer',en:'to impose'},
  {fr:'imprimer',en:'to print'},
  {fr:'inclure',en:'to include'},
  {fr:'indiquer',en:'to indicate'},
  {fr:'informer',en:'to inform'},
  {fr:'insister',en:'to insist'},
  {fr:'inspirer',en:'to inspire'},
  {fr:'interdire',en:'to forbid'},
  {fr:'introduire',en:'to introduce'},
  {fr:'inventer',en:'to invent'},
  {fr:'inviter',en:'to invite'},
  {fr:'isoler',en:'to isolate'},
  {fr:'lancer',en:'to throw, to launch'},
  {fr:'libérer',en:'to free, to release'},
  {fr:'livrer',en:'to deliver'},
  {fr:'louer',en:'to rent, to praise'},
  {fr:'maintenir',en:'to maintain'},
  {fr:'manipuler',en:'to manipulate'},
  {fr:'marquer',en:'to mark, to score'},
  {fr:'mélanger',en:'to mix'},
  {fr:'menacer',en:'to threaten'},
  {fr:'mesurer',en:'to measure'},
  {fr:'modifier',en:'to modify'},
  {fr:'multiplier',en:'to multiply'},
  {fr:'noter',en:'to note'},
  {fr:'nourrir',en:'to feed'},
  {fr:'observer',en:'to observe'},
  {fr:'organiser',en:'to organize'},
  {fr:'pardonner',en:'to forgive'},
  {fr:'partager',en:'to share'},
  {fr:'pénétrer',en:'to penetrate'},
  {fr:'perfectionner',en:'to perfect'},
  {fr:'placer',en:'to place'},
  {fr:'plonger',en:'to dive, to plunge'},
  {fr:'posséder',en:'to possess'},
  {fr:'poursuivre',en:'to pursue, to continue'},
  {fr:'pratiquer',en:'to practice'},
  {fr:'préciser',en:'to specify'},
  {fr:'préférer',en:'to prefer'},
  {fr:'prévenir',en:'to warn, to prevent'},
  {fr:'prévoir',en:'to foresee, to plan'},
  {fr:'priver',en:'to deprive'},
  {fr:'procéder',en:'to proceed'},
  {fr:'profiter',en:'to take advantage'},
  {fr:'programmer',en:'to program'},
  {fr:'projeter',en:'to project, to plan'},
  {fr:'publier',en:'to publish'},
  {fr:'punir',en:'to punish'},
  {fr:'rassembler',en:'to gather'},
  {fr:'réagir',en:'to react'},
  {fr:'réaliser',en:'to realize, to achieve'},
  {fr:'recommander',en:'to recommend'},
  {fr:'rédiger',en:'to write, to draft'},
  {fr:'réduire',en:'to reduce'},
  {fr:'réfléchir',en:'to reflect, to think'},
  {fr:'reformer',en:'to reform'},
  {fr:'refroidir',en:'to cool down'},
  {fr:'regretter',en:'to regret'},
  {fr:'rejeter',en:'to reject'},
  {fr:'remarquer',en:'to notice'},
  {fr:'remercier',en:'to thank'},
  {fr:'remplacer',en:'to replace'},
  {fr:'remplir',en:'to fill'},
  {fr:'renoncer',en:'to give up'},
  {fr:'renseigner',en:'to inform'},
  {fr:'répéter',en:'to repeat'},
  {fr:'résister',en:'to resist'},
  {fr:'résoudre',en:'to solve'},
  {fr:'respecter',en:'to respect'},
  {fr:'respirer',en:'to breathe'},
  {fr:'retirer',en:'to withdraw'},
  {fr:'retourner',en:'to return'},
  {fr:'réunir',en:'to gather, to unite'},
  {fr:'révéler',en:'to reveal'},
  {fr:'saluer',en:'to greet'},
  {fr:'satisfaire',en:'to satisfy'},
  {fr:'sélectionner',en:'to select'},
  {fr:'séparer',en:'to separate'},
  {fr:'signaler',en:'to report, to signal'},
  {fr:'signer',en:'to sign'},
  {fr:'simplifier',en:'to simplify'},
  {fr:'situer',en:'to locate'},
  {fr:'sonner',en:'to ring'},
  {fr:'souhaiter',en:'to wish'},
  {fr:'soulever',en:'to lift'},
  {fr:'soumettre',en:'to submit'},
  {fr:'soupçonner',en:'to suspect'},
  {fr:'soutenir',en:'to support'},
  {fr:'stopper',en:'to stop'},
  {fr:'subir',en:'to undergo'},
  {fr:'succéder',en:'to succeed (follow)'},
  {fr:'suggérer',en:'to suggest'},
  {fr:'supprimer',en:'to delete, to remove'},
  {fr:'survivre',en:'to survive'},
  {fr:'témoigner',en:'to testify'},
  {fr:'tenter',en:'to attempt'},
  {fr:'terminer',en:'to finish'},
  {fr:'tester',en:'to test'},
  {fr:'transformer',en:'to transform'},
  {fr:'transmettre',en:'to transmit'},
  {fr:'transporter',en:'to transport'},
  {fr:'traiter',en:'to treat, to process'},
  {fr:'trembler',en:'to tremble'},
  {fr:'triompher',en:'to triumph'},
  {fr:'tromper',en:'to deceive'},
  {fr:'troubler',en:'to disturb'},
  {fr:'vérifier',en:'to verify'},
  {fr:'verser',en:'to pour'},
  {fr:'visiter',en:'to visit (a place)'},
  {fr:'absolument',en:'absolutely'},
  {fr:'actuellement',en:'currently'},
  {fr:'ailleurs',en:'elsewhere'},
  {fr:'ainsi',en:'thus, so'},
  {fr:'apparemment',en:'apparently'},
  {fr:'auparavant',en:'before, previously'},
  {fr:'autrefois',en:'formerly'},
  {fr:'davantage',en:'more'},
  {fr:'définitivement',en:'definitely'},
  {fr:'désormais',en:'from now on'},
  {fr:'dorénavant',en:'henceforth'},
  {fr:'effectivement',en:'indeed'},
  {fr:'également',en:'also, equally'},
  {fr:'éventuellement',en:'possibly'},
  {fr:'évidemment',en:'obviously'},
  {fr:'finalement',en:'finally'},
  {fr:'franchement',en:'frankly'},
  {fr:'généralement',en:'generally'},
  {fr:'habituellement',en:'usually'},
  {fr:'heureusement',en:'fortunately'},
  {fr:'immédiatement',en:'immediately'},
  {fr:'justement',en:'precisely, exactly'},
  {fr:'malheureusement',en:'unfortunately'},
  {fr:'naturellement',en:'naturally'},
  {fr:'néanmoins',en:'nevertheless'},
  {fr:'normalement',en:'normally'},
  {fr:'particulièrement',en:'particularly'},
  {fr:'personnellement',en:'personally'},
  {fr:'progressivement',en:'gradually'},
  {fr:'rapidement',en:'rapidly'},
  {fr:'récemment',en:'recently'},
  {fr:'régulièrement',en:'regularly'},
  {fr:'relativement',en:'relatively'},
  {fr:'sérieusement',en:'seriously'},
  {fr:'sincèrement',en:'sincerely'},
  {fr:'suffisamment',en:'sufficiently'},
  {fr:'tellement',en:'so much'},
  {fr:'totalement',en:'totally'},
  {fr:'uniquement',en:'only, solely'},
  {fr:'volontiers',en:'gladly, willingly'},
  {fr:'absence',en:'absence'},
  {fr:'apparence',en:'appearance'},
  {fr:'attitude',en:'attitude'},
  {fr:'avis',en:'opinion'},
  {fr:'capacité',en:'capacity'},
  {fr:'caractère',en:'character'},
  {fr:'catégorie',en:'category'},
  {fr:'climat',en:'climate'},
  {fr:'collection',en:'collection'},
  {fr:'communauté',en:'community'},
  {fr:'communication',en:'communication'},
  {fr:'comportement',en:'behavior'},
  {fr:'concept',en:'concept'},
  {fr:'conscience',en:'conscience'},
  {fr:'construction',en:'construction'},
  {fr:'contribution',en:'contribution'},
  {fr:'contraire',en:'opposite'},
  {fr:'courage',en:'courage'},
  {fr:'création',en:'creation'},
  {fr:'crise',en:'crisis'},
  {fr:'curiosité',en:'curiosity'},
  {fr:'défaut',en:'flaw, default'},
  {fr:'demande',en:'request, demand'},
  {fr:'dessin',en:'drawing'},
  {fr:'détail',en:'detail'},
  {fr:'dimension',en:'dimension'},
  {fr:'discipline',en:'discipline'},
  {fr:'doute',en:'doubt'},
  {fr:'émotion',en:'emotion'},
  {fr:'énergie',en:'energy'},
  {fr:'engagement',en:'commitment'},
  {fr:'envie',en:'desire, craving'},
  {fr:'environnement',en:'environment'},
  {fr:'époque',en:'era, period'},
  {fr:'équilibre',en:'balance'},
  {fr:'événement',en:'event'},
  {fr:'existence',en:'existence'},
  {fr:'expression',en:'expression'},
  {fr:'faiblesse',en:'weakness'},
  {fr:'foi',en:'faith'},
  {fr:'fonction',en:'function'},
  {fr:'fortune',en:'fortune'},
  {fr:'génération',en:'generation'},
  {fr:'habitation',en:'housing'},
  {fr:'harmonie',en:'harmony'},
  {fr:'héritage',en:'heritage'},
  {fr:'identité',en:'identity'},
  {fr:'imagination',en:'imagination'},
  {fr:'impression',en:'impression'},
  {fr:'indépendance',en:'independence'},
  {fr:'inquiétude',en:'worry'},
  {fr:'inspiration',en:'inspiration'},
  {fr:'intérêt',en:'interest'},
  {fr:'logique',en:'logic'},
  {fr:'majorité',en:'majority'},
  {fr:'manière',en:'manner, way'},
  {fr:'minorité',en:'minority'},
  {fr:'mode',en:'fashion, mode'},
  {fr:'morale',en:'morals'},
  {fr:'nature',en:'nature'},
  {fr:'nécessité',en:'necessity'},
  {fr:'niveau',en:'level'},
  {fr:'norme',en:'norm'},
  {fr:'notion',en:'notion'},
  {fr:'objet',en:'object'},
  {fr:'origine',en:'origin'},
  {fr:'ouverture',en:'opening'},
  {fr:'patience',en:'patience'},
  {fr:'personnalité',en:'personality'},
  {fr:'perspective',en:'perspective'},
  {fr:'phénomène',en:'phenomenon'},
  {fr:'position',en:'position'},
  {fr:'pratique',en:'practice'},
  {fr:'principe',en:'principle'},
  {fr:'priorité',en:'priority'},
  {fr:'profession',en:'profession'},
  {fr:'profondeur',en:'depth'},
  {fr:'proportion',en:'proportion'},
  {fr:'proposition',en:'proposal'},
  {fr:'puissance',en:'power'},
  {fr:'rapport',en:'report, relationship'},
  {fr:'réaction',en:'reaction'},
  {fr:'réalité',en:'reality'},
  {fr:'réflexion',en:'reflection'},
  {fr:'relation',en:'relationship'},
  {fr:'richesse',en:'wealth'},
  {fr:'rôle',en:'role'},
  {fr:'scène',en:'scene'},
  {fr:'sensation',en:'sensation'},
  {fr:'sentiment',en:'feeling'},
  {fr:'série',en:'series'},
  {fr:'service',en:'service'},
  {fr:'signification',en:'meaning'},
  {fr:'source',en:'source'},
  {fr:'spécialité',en:'specialty'},
  {fr:'style',en:'style'},
  {fr:'substance',en:'substance'},
  {fr:'talent',en:'talent'},
  {fr:'technique',en:'technique'},
  {fr:'tempérament',en:'temperament'},
  {fr:'tendance',en:'tendency'},
  {fr:'tension',en:'tension'},
  {fr:'théorie',en:'theory'},
  {fr:'tolérance',en:'tolerance'},
  {fr:'transformation',en:'transformation'},
  {fr:'unité',en:'unity'},
  {fr:'usage',en:'usage'},
  {fr:'utilité',en:'usefulness'},
  {fr:'valeur',en:'value'},
  {fr:'variété',en:'variety'},
  {fr:'version',en:'version'},
  {fr:'voisinage',en:'neighborhood'},
  {fr:'volonté',en:'will, willpower'},
  {fr:'zone',en:'zone'},
  {fr:'allumette',en:'match (fire)'},
  {fr:'ampoule',en:'light bulb'},
  {fr:'appareil',en:'device'},
  {fr:'balai',en:'broom'},
  {fr:'balcon',en:'balcony'},
  {fr:'baignoire',en:'bathtub'},
  {fr:'boîte',en:'box'},
  {fr:'bouchon',en:'cap, cork'},
  {fr:'brosse',en:'brush'},
  {fr:'calendrier',en:'calendar'},
  {fr:'casserole',en:'saucepan'},
  {fr:'cave',en:'cellar'},
  {fr:'cendrier',en:'ashtray'},
  {fr:'cintre',en:'hanger'},
  {fr:'ciseaux',en:'scissors'},
  {fr:'coffre',en:'trunk, chest'},
  {fr:'commode',en:'dresser'},
  {fr:'congélateur',en:'freezer'},
  {fr:'couverture',en:'blanket'},
  {fr:'drap',en:'sheet'},
  {fr:'éponge',en:'sponge'},
  {fr:'étagère',en:'shelf'},
  {fr:'four',en:'oven'},
  {fr:'frigo',en:'fridge'},
  {fr:'garage',en:'garage'},
  {fr:'grenier',en:'attic'},
  {fr:'horloge',en:'clock'},
  {fr:'interrupteur',en:'switch'},
  {fr:'matelas',en:'mattress'},
  {fr:'nappe',en:'tablecloth'},
  {fr:'oreiller',en:'pillow'},
  {fr:'placard',en:'cupboard'},
  {fr:'poêle',en:'frying pan'},
  {fr:'poubelle',en:'trash can'},
  {fr:'prise',en:'outlet, socket'},
  {fr:'radiateur',en:'radiator'},
  {fr:'rasoir',en:'razor'},
  {fr:'robinet',en:'faucet'},
  {fr:'savon',en:'soap'},
  {fr:'seau',en:'bucket'},
  {fr:'serrure',en:'lock'},
  {fr:'tiroir',en:'drawer'},
  {fr:'torchon',en:'dish towel'},
  {fr:'ventilateur',en:'fan'},
  {fr:'cheville',en:'ankle'},
  {fr:'coude',en:'elbow'},
  {fr:'crâne',en:'skull'},
  {fr:'cuisse',en:'thigh'},
  {fr:'fesse',en:'buttock'},
  {fr:'foie',en:'liver'},
  {fr:'front',en:'forehead'},
  {fr:'hanche',en:'hip'},
  {fr:'intestin',en:'intestine'},
  {fr:'joue',en:'cheek'},
  {fr:'mâchoire',en:'jaw'},
  {fr:'menton',en:'chin'},
  {fr:'mollet',en:'calf (leg)'},
  {fr:'muscle',en:'muscle'},
  {fr:'nerf',en:'nerve'},
  {fr:'nuque',en:'nape (of neck)'},
  {fr:'orteil',en:'toe'},
  {fr:'paupière',en:'eyelid'},
  {fr:'poignet',en:'wrist'},
  {fr:'poitrine',en:'chest'},
  {fr:'pouce',en:'thumb'},
  {fr:'rein',en:'kidney'},
  {fr:'sourcil',en:'eyebrow'},
  {fr:'talon',en:'heel'},
  {fr:'tempe',en:'temple (head)'},
  {fr:'veine',en:'vein'},
  {fr:'allergie',en:'allergy'},
  {fr:'angine',en:'tonsillitis'},
  {fr:'bronchite',en:'bronchitis'},
  {fr:'brûlure',en:'burn'},
  {fr:'contusion',en:'bruise'},
  {fr:'crampe',en:'cramp'},
  {fr:'crise cardiaque',en:'heart attack'},
  {fr:'entorse',en:'sprain'},
  {fr:'fracture',en:'fracture'},
  {fr:'grippe',en:'flu'},
  {fr:'infection',en:'infection'},
  {fr:'inflammation',en:'inflammation'},
  {fr:'insomnie',en:'insomnia'},
  {fr:'intoxication',en:'poisoning'},
  {fr:'migraine',en:'migraine'},
  {fr:'nausée',en:'nausea'},
  {fr:'otite',en:'ear infection'},
  {fr:'rhumatisme',en:'rheumatism'},
  {fr:'rhume',en:'cold (illness)'},
  {fr:'toux',en:'cough'},
  {fr:'vertige',en:'dizziness'},
  {fr:'quelqu\'un',en:'someone'},
  {fr:'quelque chose',en:'something'},
  {fr:'chacun',en:'each one'},
  {fr:'plusieurs',en:'several'},
  {fr:'autrui',en:'others'},
  {fr:'soi',en:'oneself'},
  {fr:'lequel',en:'which one'},
  {fr:'laquelle',en:'which one (fem.)'},
  {fr:'dont',en:'whose, of which'},
  {fr:'celui-ci',en:'this one (masc.)'},
  {fr:'celle-ci',en:'this one (fem.)'},
  {fr:'ceux-ci',en:'these ones'},
  {fr:'celles-ci',en:'these ones (fem.)'},
  {fr:'pareil',en:'same, similar'},
  {fr:'tel',en:'such'},
  {fr:'nul',en:'null, no one'},
  {fr:'quiconque',en:'whoever'},
  {fr:'température',en:'temperature'},
  {fr:'degré',en:'degree'},
  {fr:'brouillard',en:'fog'},
  {fr:'tempête',en:'storm'},
  {fr:'gelée',en:'frost'},
  {fr:'grêle',en:'hail'},
  {fr:'sécheresse',en:'drought'},
  {fr:'inondation',en:'flood'},
  {fr:'canicule',en:'heat wave'},
  {fr:'brise',en:'breeze'},
  {fr:'rosée',en:'dew'},
  {fr:'verglas',en:'black ice'},
  {fr:'conférence',en:'conference'},
  {fr:'présentation',en:'presentation'},
  {fr:'formation',en:'training'},
  {fr:'promotion',en:'promotion'},
  {fr:'retraite',en:'retirement'},
  {fr:'chômage',en:'unemployment'},
  {fr:'grève',en:'strike'},
  {fr:'syndicat',en:'union'},
  {fr:'stagiaire',en:'intern'},
  {fr:'candidat',en:'candidate'},
  {fr:'entretien',en:'interview'},
  {fr:'curriculum',en:'resume'},
  {fr:'compétence',en:'skill'},
  {fr:'qualification',en:'qualification'},
  {fr:'classe',en:'class'},
  {fr:'cours',en:'course, class'},
  {fr:'matière',en:'subject'},
  {fr:'bulletin',en:'report card'},
  {fr:'tableau',en:'board, painting'},
  {fr:'craie',en:'chalk'},
  {fr:'gomme',en:'eraser'},
  {fr:'trousse',en:'pencil case'},
  {fr:'cartable',en:'school bag'},
  {fr:'récréation',en:'recess'},
  {fr:'cantine',en:'cafeteria'},
  {fr:'cour',en:'yard, court'},
  {fr:'dictionnaire',en:'dictionary'},
  {fr:'encyclopédie',en:'encyclopedia'},
  {fr:'atlas',en:'atlas'},
  {fr:'chapitre',en:'chapter'},
  {fr:'titre',en:'title'},
  {fr:'personnage',en:'character'},
  {fr:'intrigue',en:'plot'},
  {fr:'résumé',en:'summary'},
  {fr:'vaisselle',en:'dishes'},
  {fr:'lessive',en:'laundry'},
  {fr:'ménage',en:'housework'},
  {fr:'repassage',en:'ironing'},
  {fr:'aspirateur',en:'vacuum cleaner'},
  {fr:'serpillière',en:'mop'},
  {fr:'détergent',en:'detergent'},
  {fr:'ordures',en:'garbage'},
  {fr:'recyclage',en:'recycling'},
  {fr:'compost',en:'compost'},
  {fr:'application',en:'application'},
  {fr:'logiciel',en:'software'},
  {fr:'matériel',en:'hardware'},
  {fr:'réseau',en:'network'},
  {fr:'connexion',en:'connection'},
  {fr:'wifi',en:'wifi'},
  {fr:'mot de passe',en:'password'},
  {fr:'fichier',en:'file'},
  {fr:'dossier',en:'folder'},
  {fr:'données',en:'data'},
  {fr:'sauvegarde',en:'backup'},
  {fr:'mise à jour',en:'update'},
  {fr:'téléchargement',en:'download'},
  {fr:'navigateur',en:'browser'},
  {fr:'site',en:'site, website'},
  {fr:'lien',en:'link'},
  {fr:'courriel',en:'email'},
  {fr:'pièce jointe',en:'attachment'},
  {fr:'imprimante',en:'printer'},
  {fr:'scanner',en:'scanner'},
  {fr:'batterie',en:'battery'},
  {fr:'chargeur',en:'charger'},
  {fr:'câble',en:'cable'},
  {fr:'chanson',en:'song'},
  {fr:'mélodie',en:'melody'},
  {fr:'rythme',en:'rhythm'},
  {fr:'instrument',en:'instrument'},
  {fr:'guitare',en:'guitar'},
  {fr:'piano',en:'piano'},
  {fr:'violon',en:'violin'},
  {fr:'flûte',en:'flute'},
  {fr:'tambour',en:'drum'},
  {fr:'trompette',en:'trumpet'},
  {fr:'orchestre',en:'orchestra'},
  {fr:'chorale',en:'choir'},
  {fr:'compositeur',en:'composer'},
  {fr:'interprète',en:'performer'},
  {fr:'répétition',en:'rehearsal'},
  {fr:'céramique',en:'ceramics'},
  {fr:'galerie',en:'gallery'},
  {fr:'oeuvre',en:'work (of art)'},
  {fr:'chef-d\'oeuvre',en:'masterpiece'},
  {fr:'portrait',en:'portrait'},
  {fr:'paysage',en:'landscape'},
  {fr:'admiration',en:'admiration'},
  {fr:'affection',en:'affection'},
  {fr:'agacement',en:'annoyance'},
  {fr:'angoisse',en:'anguish'},
  {fr:'anxiété',en:'anxiety'},
  {fr:'compassion',en:'compassion'},
  {fr:'déception',en:'disappointment'},
  {fr:'dégoût',en:'disgust'},
  {fr:'désespoir',en:'despair'},
  {fr:'embarras',en:'embarrassment'},
  {fr:'enthousiasme',en:'enthusiasm'},
  {fr:'fierté',en:'pride'},
  {fr:'frustration',en:'frustration'},
  {fr:'gratitude',en:'gratitude'},
  {fr:'honte',en:'shame'},
  {fr:'impatience',en:'impatience'},
  {fr:'indifférence',en:'indifference'},
  {fr:'méfiance',en:'distrust'},
  {fr:'mélancolie',en:'melancholy'},
  {fr:'nostalgie',en:'nostalgia'},
  {fr:'optimisme',en:'optimism'},
  {fr:'pessimisme',en:'pessimism'},
  {fr:'pitié',en:'pity'},
  {fr:'regret',en:'regret'},
  {fr:'remords',en:'remorse'},
  {fr:'résignation',en:'resignation'},
  {fr:'satisfaction',en:'satisfaction'},
  {fr:'soulagement',en:'relief'},
  {fr:'stupeur',en:'stupor'},
  {fr:'sympathie',en:'sympathy'},
  {fr:'terreur',en:'terror'},
  {fr:'timidité',en:'shyness'},
  {fr:'approximativement',en:'approximately'},
  {fr:'brièvement',en:'briefly'},
  {fr:'clairement',en:'clearly'},
  {fr:'complètement',en:'completely'},
  {fr:'constamment',en:'constantly'},
  {fr:'couramment',en:'fluently'},
  {fr:'discrètement',en:'discreetly'},
  {fr:'efficacement',en:'efficiently'},
  {fr:'énormément',en:'enormously'},
  {fr:'entièrement',en:'entirely'},
  {fr:'essentiellement',en:'essentially'},
  {fr:'excessivement',en:'excessively'},
  {fr:'extrêmement',en:'extremely'},
  {fr:'facilement',en:'easily'},
  {fr:'fréquemment',en:'frequently'},
  {fr:'gratuitement',en:'for free'},
  {fr:'honnêtement',en:'honestly'},
  {fr:'légèrement',en:'slightly'},
  {fr:'librement',en:'freely'},
  {fr:'longuement',en:'at length'},
  {fr:'mécaniquement',en:'mechanically'},
  {fr:'modestement',en:'modestly'},
  {fr:'mystérieusement',en:'mysteriously'},
  {fr:'négligemment',en:'carelessly'},
  {fr:'ouvertement',en:'openly'},
  {fr:'paisiblement',en:'peacefully'},
  {fr:'patiemment',en:'patiently'},
  {fr:'poliment',en:'politely'},
  {fr:'précédemment',en:'previously'},
  {fr:'principalement',en:'mainly'},
  {fr:'profondément',en:'deeply'},
  {fr:'prudemment',en:'cautiously'},
  {fr:'publiquement',en:'publicly'},
  {fr:'radicalement',en:'radically'},
  {fr:'secrètement',en:'secretly'},
  {fr:'silencieusement',en:'silently'},
  {fr:'simplement',en:'simply'},
  {fr:'spontanément',en:'spontaneously'},
  {fr:'strictement',en:'strictly'},
  {fr:'subitement',en:'suddenly'},
  {fr:'violemment',en:'violently'},
];
